### ISSUE TITLE
Build in TestFlight - App closes immediately after opening

### ISSUE THREAD

**Issue by ricardokdz** [pmwisdom/cordova-background-geolocation-services#55] opened 2016-09-13 09:40 UTC
I use cordova version: `6.3.1`

Only iOS , android works normal.

Without making any call plugin code in the error happens . Just load the library plugin already happens the error.

It works perfectly on iOS Simulator 9.3 and running on the device, also 9.3.

Only when I make the file to start the production process, the error happens in TestFlight.

Whenever I build ios the cord , and open the project in Xcode , I am asked to convert the code to the new standard Swift.

If I say yes, build error. If I say do not build works and error in TestFlight .

I've read all repository issues have not found anything like it.

I tried to include , without success: `<preference name="deployment-target" value="7.0" />`

Device log:

```
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa securityd[89] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa securityd[89] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa amfid[179] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa kernel[0] <Notice>: xpcproxy[962] Container: /private/var/mobile/Containers/Data/Application/335409B2-A379-416F-824B-3F33B1EB5F39 (sandbox)
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa com.apple.xpc.launchd[1] (UIKitApplication:com.brave.garupa[0xd966][962]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa assertiond[63] <Warning>: Unable to obtain a task name port right for pid 962: (os/kern) failure (5)
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Warning>: Unable to register for exec notifications: No such process
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Warning>: Unable to obtain a task name port right for pid 962: (os/kern) failure (5)
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Warning>: Unable to obtain a task name port right for <FBApplicationProcess: 0x130e62bb0; com.brave.garupa; pid: 962>
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Warning>: Application 'UIKitApplication:com.brave.garupa[0xd966]' crashed.
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa SpringBoard[54] <Warning>: Application '(null)' exited for an unknown reason.
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa ReportCrash[963] <Notice>: Formulating report for corpse[962] Garupa
Sep 13 06:25:47 iPhone-de-Ricardo-Pedrosa ReportCrash[963] <Warning>: Saved type '109(109_Garupa)' report (1 of max 25) at /var/mobile/Library/Logs/CrashReporter/Garupa-2016-09-13-062547.ips.beta
```

**Comment by pmwisdom** [comment] 2016-09-30 17:09
If you remove the plugin does the test flight build then run successfully?

I have an application in test flight that is still working with the plugin installed.

**Comment by ricardokdz** [comment] 2016-09-30 17:49
Yes, i upload a lot test versions, all failed.

If remove only plugin, nothing more. Works perfectly.

**Comment by pmwisdom** [comment] 2016-10-02 20:52
It's possible that its because of the new swift version. I'm working on converting it over if you want to give it a try after I'm finished.

**Comment by srsarcasmo** [comment] 2016-10-07 15:08
I have a friend  problem, I already have this service running biuen; but the problem is I have a function called AutoUpload that is in javascritp that only runs once when the application will give background .. tell me how to make this application by sensing the ubivaciones and both the sending my function this AutoUpload
  My role AutoUpload is in an interval of every 3 minutes and only do it once cuyando close the application and not working when the application is in background

**Comment by mamutkin** [comment] 2016-10-17 07:37
Check variable EMBEDDED_CONTENT_CONTAINS_SWIFT must be YES in your building settings.
![dobra xcodeproj 2016-10-17 10-38-49](https://cloud.githubusercontent.com/assets/22716360/19428996/0081e692-9456-11e6-9789-9cf1405e4fd7.png)

**Comment by pmwisdom** [comment] 2017-01-15 21:31
Fixed in new verison.

**Closed as completed by pmwisdom** 2017-01-15 21:31 UTC
