### ISSUE TITLE
background service crashed when app is closed 

### ISSUE THREAD

**Issue by cosmicanant** [pmwisdom/cordova-background-geolocation-services#28] opened 2016-06-27 04:44 UTC
Hi 
I am wondering if I can track location even if the app is closed. Currently after closing app, background service is also get crashed. Please let me know if somehow we can do this.

**Comment by pmwisdom** [comment] 2016-06-28 15:22
@cosmicanant : Do you mean closed as in force closed by user?

**Comment by pmwisdom** [comment] 2016-08-06 21:52
Closing this as its been answered in other places.
If the user force closes the app, the background service will turn off by design.

**Closed as completed by pmwisdom** 2016-08-06 21:52 UTC
