### ISSUE TITLE
Tracking on locked phone

### ISSUE THREAD

**Issue by icedice** [pmwisdom/cordova-background-geolocation-services#15] opened 2016-04-12 12:24 UTC
1) should this be working when my device (android) screen is off? cause I'm having a hard time getting that to work, when app in background and sceen is unlocked all is good.

2) When not moving it stops tracking to save power, which is awsome. But it never seems to start again, is this by design or am I missing something.

**Comment by pmwisdom** [comment] 2016-04-12 16:12
It should always be tracking, no matter what state your phone is in (in the background), unless you've force closed it of course.

It should restart whenever you A. Start moving again (when detected activities is activated) , and B. Move past the distance filter you've set. Once those two conditions are met it will start tracking again. 

I'm going to throw up a demo later this week that you can try if your still having issues.

**Comment by icedice** [comment] 2016-04-13 06:25
Thanks for the quick answer.  Background tracking is a crucial part of a app that I'm working on which has to be live within a few month, so I'm really happy you are helping me out here. I will keep working on it later to day when I get to work, but a working example would also be great! 

I'll be using it to send coords to my rest backend which then will send out push messages to devices that are within range of certain targets.

**Comment by icedice** [comment] 2016-04-13 13:56
Still not getting the results I'm hoping for. Also I seem to get popups about activity changes even with debug: false...

**Comment by pmwisdom** [comment] 2016-04-13 20:57
Latest commit should obliterate those pesky toast messages. I'm going to go ahead and run the plugin all day and make sure there isn't something wrong, but I haven't had a problem with it not tracking yet.

What happens if you turn detectedActivities off?

**Comment by pmwisdom** [comment] 2016-04-13 20:58
A.K.A set useActivityDetection : false

**Comment by icedice** [comment] 2016-04-14 07:07
Thank you. I'll try with detectedActivities off. What settings do you use? I was just using the settings from you example. Also I will update to latest to get rid of the toasts.

On my way to work (~15min walk and bus) I got 64 events (activity changes and gps coords) which my sample app sends to loggly. But only 4 was coords, the rest was activity changes....

By the way, I'm not quite sure what the desiredAccuracy and fastestInterval options does...

Just to be clear the settings I used was the aggressive ones from your example (interval 9000, fastest 5000, accuracy 20, distance 5) not the default ones from BackgroundLocationServices.js

**Comment by icedice** [comment] 2016-04-14 07:14
By the way, I'm not quite sure what the desiredAccuracy and fastestInterval options does...

**Comment by icedice** [comment] 2016-04-14 07:56
Disabling debug toast works like a charm now. I would be great if you updated the plugin version when you commit changes :) 

I'm seeing this when compiling 
`Note: D:\projects\JobOnTheRun\geo3\platforms\android\src\com\flybuy\cordova\location\BackgroundLocationUpdateService.java uses unchecked or unsafe operations.
`
should I worry about that?

By the way my sample app is here: https://bitbucket.org/monkeystyle/cordova-background-gps-poc/

**Comment by pmwisdom** [comment] 2016-04-14 15:00
For settings it depends, I usually want aggressive tracking, since its my own device. There are short descriptions of what each does in the README, but basically : 

Desired Accuracy (Lower Means More Accurate) : Determines how much power the GPS gets while obtaining coordinates, which directly translates into how accurate the GPS coordinates you get back are.  There is an accuracy number passed back with the location, which tells you how confident the device is that the coordinate that it sent back is where you actually are. (gps isnt 100% accurate). 

Fastest Interval, which is only on android, tells the device the fastest interval that you want GPS coordinates handed back to you. Basically, how many updates your server / device wants to handle in MS. Basically you shouldn't get coordinates faster than your fastest interval. 

If you want aggressive tracking, set distance : 0, desiredAccuracy : 0.

**Comment by pmwisdom** [comment] 2016-04-14 15:01
And no don't worry about those warnings. I'll take a look at your code and put it up in the README as a sample. Thanks!

**Comment by tomasmasek** [comment] 2016-04-15 17:07
Hi, the plugins works great! However, I can confirm previously mentioned bug - tracking stops few seconds after the device goes to standby mode (screen off).
(tested on some Huawei ALE L21)

**Comment by pmwisdom** [comment] 2016-04-15 17:09
Android or iOS?

**Comment by tomasmasek** [comment] 2016-04-15 17:16
Android! Not tested on iOS yet.

**Comment by icedice** [comment] 2016-04-15 18:01
hmmm my test device is Huawei ALE L21 too.. maybe it's a EMUI issue?

**Comment by pmwisdom** [comment] 2016-04-15 18:07
@tomasmasek have you tried with useActivityDetection : false?

**Comment by icedice** [comment] 2016-04-15 18:08
could be related: https://support.strava.com/hc/en-us/articles/216942547-How-to-fix-GPS-recording-issues-on-Huawei-Ascend-P7

**Comment by tomasmasek** [comment] 2016-04-15 18:24
OK, got it! I had to set my demo app as "protected" in android power management settings.
Since I'm an iOS user, I didn't know about such setting in Android.
Everything works well now, but I'll keep testing and keep you updated, if there will be something new.
Thank you for help guys.

**Comment by icedice** [comment] 2016-04-15 18:32
Cools. Let's hear how it goes, I'm still having trouble getting frequent enough updates... I need one every 2 min or so (when moving)...

**Comment by pmwisdom** [comment] 2016-04-15 18:55
Try these options, which are basically the most aggressive : 

```
{
    desiredAccuracy:      0, 
    distanceFilter:       0, 
    debug:                false, 
    interval:             2000, 
    fastestInterval:      1000, 
    useActivityDetection: false 
  }
```

**Comment by icedice** [comment] 2016-04-15 19:00
Super, I will try that.

**Comment by icedice** [comment] 2016-04-20 06:40
I changed to a S5 as my test device. Everything is working perfect now! I'm getting more than enough coords. Now i just need to tweak the settings to my needs. Also I will start testing on iOS soon. Any chance of a WP version of the plugin?

**Comment by pmwisdom** [comment] 2016-04-20 13:07
@icedice no plan for Windows Phone support since I don't have any test devices.

Glad you got the S5 working though!

**Comment by icedice** [comment] 2016-04-20 16:23
Too bad :( I'm going to need WP support very soon. I might just port your plugin to WP if i got the skills :)

**Comment by pmwisdom** [comment] 2016-04-21 01:18
Awesome, let me know if you start that up and i'll help in any way I can.

**Closed as completed** 2016-05-30 19:57 UTC
